### ISSUE TITLE
odd path behavior

### ISSUE THREAD

**Issue by jimmckeeth** [HashLoad/boss#104]
When I first run boss it modifies my path adding `;C:\Users\[USER]\.boss\env\dcp;` The extra semicolons cause blank path entries. 

I close my console window, and run boss version again, and it tells me to restart my console because it added another directory to my path `C:\Users\[USER]\.boss\env\dcu`

- On the 3rd run my path is modified again: `C:\Users\[USER]\.boss\env\bpl`
- 4th run `C:\Users\[USER]\.boss\modules\.bin`
- 5th run `.\modules\.bin`
- 6th run it stops prompting me to restart my console and stops modifying my path

**Comment by jimmckeeth** [comment]
I tried this in two different Windows 11 installs.

**Comment by snakeice** [comment]
Fixed on [c3ade35](https://github.com/HashLoad/boss/commit/c3ade3561936d61912dfd15d806450ffe4f57336)
