### ISSUE TITLE
Boss update

### ISSUE THREAD

**Issue by fabiohmribeiro** [HashLoad/boss#120]
Ao utilizar o comando boss update, é feito a atualização das dependências no boss-lock.json. 
No boss.json não deveria, também, atualizar a versão da release?

![image](https://user-images.githubusercontent.com/12716381/195881405-231f5b4a-cd21-4576-a9bb-78a3e7956bf3.png)

**Comment by viniciussanchez** [comment]
O boss.json vai salvar a versão que você instalou. o boss-lock.json é a versão que está usando atualmente. A intensão é exatamente essa, mas se tiver alguma sugestão...
