### ISSUE TITLE
Erro ao baixar projeto privado do Bitbucket usando chave ssh

### ISSUE THREAD

**Issue by rafaelevoinfo** [HashLoad/boss#127]
Olá, estou tentando usar o boss para realizar a instalação de uma dependência que está em um projeto privado no bitbucket. 
Já realizei o comando 
`boss login bitbucket.org` 
informando o endereço da minha chave ssh privada, em seguida realizei um 
`boss install git@bitbucket.org:team/meu_projeto_privado.git`
porém me retorna o seguinte erro
[INFO ] Downloading dependency github.com/git@bitbucket.org:team/meu_projeto_privado
[ERROR] Error to get repository of github.com/git@bitbucket.org:team/meu_projeto_privado: unexpected client error: unexpected requesting "https://github.com/git@bitbucket.org:team/meu_projeto_privado/info/refs?service=git-upload-pack" status code: 40

Não sei porque ele sempre adiciona um prefixo com o endereço do github.com
Estou esquecendo de algum passo?

**Comment by andre-djsystem** [comment]
Informe uma URL válida, que possa ser acessada via browser.

**Comment by rafaelevoinfo** [comment]
Eu tentei com as seguintes combinações e nenhuma funcionou:

1. https://bitbucket.org/team/meu_projeto_privado
2. https://usuario@bitbucket.org/team/meu_projeto_privado.git

**Comment by rafaelevoinfo** [comment]
Descobri o problema, não se pode colocar o https. Usando o seguinte comando deu certo.
`boss install bitbucket.org/team/meu_projeto_privado`

Obrigado.
