### ISSUE TITLE
Utilizar Gitlab como repositório

### ISSUE THREAD

**Issue by gamboajorge49** [HashLoad/boss#128]
olá, estou tentando utilizar o boss com uma instancia propria do gitlab. Fiz toda a configuração da chave ssh, mas quando tento adicionar a dependência da o erro, onde ele concatena a url do github com o caminho do clone ssh.

Preciso fazer alguma configuração especifica ou o boss não tem suporte ao gitlab ?

**Caminho do clone ssh: git@192.168.1.132:jorge_gamboa/mapnet.git**

**boss i git@192.168.1.132:jorge_gamboa/mapnet.git**

[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency mapnet
[INFO ] Downloading dependency github.com/git@192.168.1.132:jorge_gamboa/mapnet
[ERROR] Error to get repository of github.com/git@192.168.1.132:jorge_gamboa/mapnet: unexpected client error: unexpected requesting "https://github.com/git@192.168.1.132:jorge_gamboa/mapnet/info/refs?service=git-upload-pack" status code: 400

**Comment by viniciussanchez** [comment]
Você fez o boss login com ssh?
tenta instalar assim:
boss install https://seudominio.com.br/projeto/exemplo/nomedoprojetonogitlab
eu uso aqui na empresa e funciona normal

**Comment by gamboajorge49** [comment]
Sim tentei, porém estou usando com o ip e sem https. Pode ser isso o problema ?

**Comment by viniciussanchez** [comment]
Imagino que não...
aqui no exemplo você fez diferente
boss i git@192.168.1.132:jorge_gamboa/mapnet.git
por isso achei que nao tinha testado
como você fez o comando boss login?

**Comment by gamboajorge49** [comment]
boss login 192.168.1.132
