### ISSUE TITLE
Mkdir error boss

### ISSUE THREAD

**Issue by viniciussanchez** [HashLoad/boss#15]
Olá, 
Fiz o download da release v2.2.1 disponível para download, seguindo as instruções para instalação, mas não funciona. Já testei em duas máquinas minhas e nada...

![image](https://user-images.githubusercontent.com/16382981/56445012-89237500-62d1-11e9-9262-1ea847ac43ad.png)
![image](https://user-images.githubusercontent.com/16382981/56445028-980a2780-62d1-11e9-9069-ca5d93a50557.png)
![image](https://user-images.githubusercontent.com/16382981/56445054-b53ef600-62d1-11e9-94b8-30d400861bf2.png)

Ao executar o comando boss version ou qualquer outro:

![image](https://user-images.githubusercontent.com/16382981/56445085-d7387880-62d1-11e9-8a46-0579a42d92f1.png)

**Comment by snakeice** [comment]
Olá, o comportamento foi causado por um erro interno, ajustado no commit 615765f e liberado na versão [v2.2.2](https://github.com/HashLoad/boss/releases/v2.2.2).
Infelizmente o comando `boss upgrade` não vai conseguir atualizar para a próxima verão, pois o erro ocorre no processo de inicialização do Boss. Poderia instalar a ultima versão [v2.2.2](https://github.com/HashLoad/boss/releases/latest) utilizando o instalador e passar o feedback sobre a ocorrência do erro pós correção para finalizarmos a issues?

Obrigado!

**Comment by snakeice** [comment]
Olá, o comportamento foi causado por um erro interno, ajustado no commit 615765f e liberado na versão [2.2.2](https://github.com/HashLoad/boss/releases/v2.2.2).
Infelizmente o comando `boss upgrade` não vai conseguir atualizar a sua versão para a próxima verão, pois o erro ocorre no processo de inicialização do Boss. Poderia instalar a ultima versão [2.2.2](https://github.com/HashLoad/boss/releases/latest) utilizando o instalador e passar o feedback sobre a ocorrência do erro pós instalação para finalizarmos a issues?

**Comment by viniciussanchez** [comment]
@snakeice acabei de testar e o problema foi resolvido...

![image](https://user-images.githubusercontent.com/16382981/56451161-bf2c1d80-6300-11e9-9f1d-2413b9a9799d.png)

Obrigado e parabéns pela agilidade na solução do problema...
Estive falando com o @hunsche esses dias sobre o projeto... eu não manjo muito de Go não.. a um tempo atras fiz um curso e gostei bastante.... mas estou a disposição se puder ajudar voces em algo... so falar...

mais uma vez obrigado...
