### ISSUE TITLE
Where to see a list of all packages?

### ISSUE THREAD

**Issue by raelb** [HashLoad/boss#151]
Hi,
Where can I see a list of all supported packages?
Thanks

**Comment by viniciussanchez** [comment]
Sorry, we don't have that list.
Typically, supported packages describe in their documentation the possibility of using Boss, as shown in the images below:

![image](https://github.com/HashLoad/boss/assets/16382981/482d73e4-2c61-40cd-91ff-663d961e47cb)

![image](https://github.com/HashLoad/boss/assets/16382981/10faef96-22e3-4914-b08f-62689e990203)

![image](https://github.com/HashLoad/boss/assets/16382981/58af8e60-58e8-44a6-926d-51bd76682f06)

![image](https://github.com/HashLoad/boss/assets/16382981/532836f3-062c-4722-8826-1a5cd06a1f5f)

![image](https://github.com/HashLoad/boss/assets/16382981/9d35d17f-a49d-40b4-9577-c85e3b283127)
