### ISSUE TITLE
How do I change the branch name?

### ISSUE THREAD

**Issue by Spelt** [HashLoad/boss#154]
Hi,

Thanks for this easy to use tool.  I do have a question:  how do I add a git module from a branch other then Master ? 

It looks like that there is logic build in for this.

Thanks, 
Edward

**Comment by viniciussanchez** [comment]
As far as I remember we don't have that option yet. What you can do is install a specific version, as in the example below:
boss install horse:1.0.0

**Comment by Spelt** [comment]
Thanks!

**Comment by sbeu** [comment]
I think BOSS does not handle branches. It uses git TAGS to identify a specific version of a package. A release is a tag.
