### ISSUE TITLE
How can I spin up a private repository by using boss?

### ISSUE THREAD

**Issue by caryyu** [HashLoad/boss#158]
Just like what title said, If I want to have a self-hosted repository, How this tool works with the server? any document to explain this? thanks. For Delphi, Does it work for changing my project file for searching the lib path? How does it work for Design Time ones?

**Comment by viniciussanchez** [comment]
Yes, you can use boss with private projects. To do this you need to do a "boss login" first. Example: boss login github.com

Always prefer to use ssh, especially with Github. To log in boss, use a terminal such as power shell, always with Administrator preference.

As for visual projects, you would need to have another library installed, which is boss-ide. He is responsible for loading on demand visual components installed with the boss.
