### ISSUE TITLE
URL da dependência LowerCase

### ISSUE THREAD

**Issue by andriwsluna** [HashLoad/boss#162]
Este trecho de código está convertendo a url da dependência para lowercase, isto faz com que servidores git com case-sensitive, como o AWS Code-Commit, não consigam resolver. 

core/installer/utils.go
```
package installer
.
.
.

func EnsureDependencyOfArgs(pkg *models.Package, args []string) {
	for e := range args {
		dependency := ParseDependency(args[e])
		dependency = strings.ToLower(dependency)
```

Fiz um teste local e retirando o `strings.ToLower(dependency)` funcionou. É realmente necessário trabalhar com LowerCase?

**Comment by viniciussanchez** [comment]
Bom dia... acredito que não... quando o servidor for case-sensitive teria problema como você mesmo pegou. E se o servidor não for case-sensitive, então isso seria irrelevante imagino eu. Se quiser enviar um pull request com a correção.. por favor

**Comment by andriwsluna** [comment]
Vou fazer. Obrigado!
