### ISSUE TITLE
Adding .dcp

### ISSUE THREAD

**Issue by viniciussanchez** [HashLoad/boss#18]
For each project added Boss adds .dcp twice. It's correct?

![image](https://user-images.githubusercontent.com/16382981/58256418-5bed3b00-7d45-11e9-8c7c-39331139eee6.png)

**Comment by snakeice** [comment]
It was with problem when giving boss install, where it ignored the existing one and added again, in the next release it will already be corrected \o/
Until the end of the week, the version is released..
