### ISSUE TITLE
boss update

### ISSUE THREAD

**Issue by viniciussanchez** [HashLoad/boss#47]
When you run the "boss update" command in a project where the modules folder is not created, it says it cannot access the directory.

When that happens, the correct thing would be for the boss to already create the folders needed to execute the boss update. That would be very helpful.

I am using v3.0.0-alpha12 version

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/62372767-b3aade00-b50e-11e9-9a93-2579d1448ba6.png)

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/62373760-d9d17d80-b510-11e9-96fd-0adfa87e4ffd.png)

**Comment by snakeice** [comment]
Adjusted
