### ISSUE TITLE
Error in "Install Package"

### ISSUE THREAD

**Issue by guimatech** [HashLoad/boss#53]
Eu tenho uma hierarquia de projetos da seguinte forma:
```
.
└── prjPrincipal:
    └── pacote1@1.0.0      
        └── pacote2@1.0.0
```

sendo assim para o que o "pacote1" seja compilado preciso que o "pacote2" seja compilado e instalado, porém o que acontece é que os pacotes são até copilados e informa que foram instalados da forma correta como no log a seguir:

```
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency pacote1
[INFO ] Installing modules
[INFO ] Processing dependency pacote1
[INFO ]   Detected semantic version. Using version 1.0.0
[INFO ] Processing module pacote1
[INFO ] Building cache files...
[INFO ] Updating cache of dependency pacote2
[INFO ] Installing modules
[INFO ] Processing dependency pacote2
[INFO ]   classesxe already updated
[INFO ] Processing module pacote2
[INFO ] Building cache files...
[INFO ] Installing modules
[INFO ] Compiling units
[INFO ] Building pacote1
[INFO ]   Building pacote1.dproj
[ERROR]   - Failed to compile, see C:\Projetos\prjPrincipal\modules\pacote1\build_boss_pacote1.log for more information
[INFO ] Success!
```

No log só diz que não encontrou determinado arquivo que devia ter sido instalado pelo "pacote2", investigando mais a fundo vi que ele até chega a apagar o pacote do Delphi, mas não coloca de novo no acesso do "Component > Install Package"

**Comment by snakeice** [comment]
Opa, como está o boss.json do pacote2?

**Comment by guimaraes-lucas** [comment]
```
{
	"name": "pacote2",
	"description": "",
	"version": "1.0.0",
	"homepage": "",
	"mainsrc": "./",
	"projects": [
		"pacote2classes.dproj",
		"pacote2registro.dproj"
	],
	"dependencies": {}
}
```
o pacote2classes é compilável somente e o pacote2registro compila e é também que instala e registra os componentes no "Component > Install Package"

**Comment by guimaraes-lucas** [comment]
> ```
> {
> 	"name": "pacote2",
> 	"description": "",
> 	"version": "1.0.0",
> 	"homepage": "",
> 	"mainsrc": "./",
> 	"projects": [
> 		"pacote2classes.dproj",
> 		"pacote2registro.dproj"
> 	],
> 	"dependencies": {}
> }
> ```
> 
> o pacote2classes é compilável somente e o pacote2registro compila e é também que instala e registra os componentes no "Component > Install Package"

**Comment by snakeice** [comment]
Consegue criar um demo para o debug?

**Comment by snakeice** [comment]
Tenho alguns projetos com uma estrutura mais complexa e nunca deu esse tipo de problema.. Qual versão do boss ta sendo usada ai?

**Comment by guimaraes-lucas** [comment]
v3.0.2

**Comment by guimaraes-lucas** [comment]
posso tentar criar a demo pra debug

**Comment by guimaraes-lucas** [comment]
@snakeice cara não consegui simular a exata situação que eu tenho aqui, que é do pkg1 não compilar por conta do 2 não ter sido instalado.
Contudo com essa situação que eu simulei você já vai notar que ele não instala o pacote no Delphi, somente compila os pacotes.
Tanto é que mesmo depois de rodar o "boss install" quando vai se abrir o projeto ele vai dar falta do componente que devia estar instalado.

Então acho que resolvendo essa situação, resolverá também a outra que estou tendo.

**Comment by snakeice** [comment]
Para instalar vc ta usando ex `boss install -g ...` ou sem o "-g", pq com isso ele instala global, se for instalar por projeto precisa do boss-ide instalado globalmente para conseguir carregar o modulos na IDE

**Comment by guimaraes-lucas** [comment]
Tentei ambos porém não instalou, uso a versão Berlim do Delphi e para essa o boss-ide tem um erro:

Solve the compilation problem in DX Berlin

 **- Problem**
```
	"<user>\.boss\modules\5a7f3942105f389501dd9b6feb076eff\modules\boss-ide\boss_ide.dproj" (Build target) (1) ->
(_PasCoreCompile target) -> 
  src\core\Boss.Modules.PackageProcessor.pas(166): error E2010: Incompatible types: 'TStringDynArray' and 'System.TArray<System.string>'
  src\core\Boss.Modules.PackageProcessor.pas(198): error E2010: Incompatible types: 'System.TArray<System.string>' and 'TStringDynArray'
  src\core\Boss.Modules.PackageProcessor.pas(245): error E2010: Incompatible types: 'System.TArray<System.string>' and 'TStringDynArray'
  boss_ide.dpk(38): error F2063: Could not compile used unit 'Boss.Modules.PackageProcessor.pas'

    1 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.24
```

 **- Solution**
	Replace 'System.TArray <System.string>' with 'TStringDynArray'

Abri um pull request que deve resolver isso, mas mesmo com o boss-ide não instala pkg corretamete.
https://github.com/HashLoad/boss-ide/pull/10

**Comment by viniciussanchez** [comment]
Bom dia, o erro ainda persiste? Podemos fechar a issue?
