### ISSUE TITLE
Error to get repository of authentication required

### ISSUE THREAD

**Issue by berttony** [HashLoad/boss#58]
Olá!
Gostaria de usar o Boss como gerenciador de dependências de projetos Delphi (Projetos REST baseados no Horse inclusive). Tenho um repositório git privado no azure Devops (TFS). Porem o boss me exige uma autenticação que não sei onde informa-la. Por restrições da equipe de infra estrutura esse repositório é HTTP e não poderá usar o HTTPS.

Exemplo de utilização:

boss install http://tfs.........../_git/exemplo
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency exemplo
[INFO ] Downloading dependency http://tfs.........../_git/exemplo
[ERROR] Error to get repository of http://tfs.........../_git/exemplo: authentication required

Tem alguma solução? podem me ajudar?

**Comment by viniciussanchez** [comment]
Olá @berttony voce tem que fazer login no boss...
só usar o comando:
```
boss login
```

**Comment by viniciussanchez** [comment]
Assista ao vídeo: 
https://www.youtube.com/watch?v=bchUVPFRUj8

**Comment by berttony** [comment]
@viniciussanchez  no meu caso o "boss login" não funcionou e se mantem a mesma mensagem de retorno. Acredito que não seja o contexto que o "boss login" trate, pois quando digo que  "Tenho um repositório git privado no azure Devops (TFS)" na verdade so tenho acesso se logar na rede local. Mas obrigado pelo retorno.

**Comment by andre-djsystem** [comment]
Abra o arquivo %UserProfile% \.boss\boss.cfg.json e altere a opção git_embedded para false

**Comment by sbeu** [comment]
I have the same problem, and git_embedded=false does not change anything :(

**Comment by marcelinoap** [comment]
Alguém conseguiu resolver este problema? Tentei como administrador e nada... Não sei o que colocar no SSH

**Comment by equinhone** [comment]
alguem teve sorte nesse erro ?
