### ISSUE TITLE
Error boss install repository from gitlab

### ISSUE THREAD

**Issue by FactorySolution** [HashLoad/boss#60]
Estou realizando o comando boss install para um repositório da empresa, gitlab, porém alguns dos repositórios esta apresentando o seguinte erro:

 Error on switch to needed version from dependency git@git.xxxxxxxxxxx reference not found

Já tentei de varias formas e mesmo assim o mesmo não realiza a instalação.

Estou usando via ssh.

**Comment by snakeice** [comment]
Can you give me the commands that were used for login and installation? Without sensitive data of course..

**Comment by FactorySolution** [comment]
Não estou utilizando login e senha, somente via ssh.

boss install git@git.xxxxxxx.

**Comment by joaoduarte19** [comment]
I'm also having trouble trying to use the boss with a repository from a local gitlab server. I execute the command `boss login` to my server and then execute `boss install`, then the error `authentication required` returns to me.

![image](https://user-images.githubusercontent.com/13373632/91670427-c3bb3580-eaf3-11ea-943a-64350af4acc9.png)
