### ISSUE TITLE
Suporte a releases com versionamento de 4 níveis

### ISSUE THREAD

**Issue by josiasmaceda** [HashLoad/boss#61]
O Boss pega a última versão do repositório com 3 níveis (através do comando boss update). Ex: 1.1.8 mesmo que no repositório tenha um release com a versão 1.1.8.1 , se forçar o boss a baixar a versão mais recente alterando a versão no arquivo .boss para 1.1.8.1 ocasiona erro;

Version type not supported! improper constraint: ^1.1.8.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x8effa5]

**Comment by snakeice** [comment]
Sorry, but the fourth part is not part of the specification :cry:... See https://semver.org/
