### ISSUE TITLE
Login GitHub

### ISSUE THREAD

**Issue by adelsoncn** [HashLoad/boss#66]
ao tentar fazer login "boss login" mesmo colocando a senha e usuário correto quando tento instalar uma dependência que é privada ele diz que é necessário fazer login

**Comment by viniciussanchez** [comment]
Olá, está fazendo conforme esse vídeo?
https://www.youtube.com/watch?v=bchUVPFRUj8

**Comment by adelsoncn** [comment]
Boa tarde

Sim , fiz exatamente igual

O boss não retorna com erro se não foi aceito o login? , porque coloquei senha errada e não mudou ... Apenas desceu para o prompt novamente

Adelson Nunes

________________________________

**Comment by viniciussanchez** [comment]
Se nao estiver enganado ele nao tenta fazer login, ele so salva para utilizar os dados ao tentar baixar um projeto privado.

**Comment by viniciussanchez** [comment]
Talvez o @snakeice possa te ajudar melhor com isso...

**Comment by snakeice** [comment]
Opa, pode passar como esta sendo feito o login e o boss install?

**Comment by snakeice** [comment]
E é isso msm, ele não valida no login :cry:, pq é mto especifico de cada provedor, até podemos planejar fazer isso para os populares (github, gitlab e bitbucket)..

**Comment by snakeice** [comment]
Resolvido por email

**Comment by rlopesbtu** [comment]
Puxa estou com o mesmo problema... o que será que foi conversado por e-mail rs

**Comment by viniciussanchez** [comment]
Executou o boss login? Como administrador? Usando o Power Shell? Com SSH?
