### ISSUE TITLE
Uninstall command

### ISSUE THREAD

**Issue by mpirescarvalho** [HashLoad/boss#69]
uninstall command is not working, it always try to install the package

![image](https://user-images.githubusercontent.com/20830847/113609038-a9b17a80-9621-11eb-8464-2fdfeaa40ee3.png)

**Comment by juliomar** [comment]
Version?

**Comment by mpirescarvalho** [comment]
Latest

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/143611008-dc1f2927-1f05-485b-ae29-e64c433908d2.png)
I took the test and it is working perfectly.
However, it uses the install function. There is a to-do for improving this process.
