### ISSUE TITLE
boss not working

### ISSUE THREAD

**Issue by WhebertonFialho** [HashLoad/boss#71]
Estou tentando instalar os pacotes via horse mas o mesmo sempre aparece a mesma mensagem de não login

![image](https://user-images.githubusercontent.com/9007678/133616580-6c36feb2-a9b7-4668-9986-bc0240e76fd8.png)

**Comment by viniciussanchez** [comment]
Bom dia... poderia passar mais informações a respeito? Eu fiz o teste aqui e aparentemente está tudo certo

![image](https://user-images.githubusercontent.com/16382981/133617792-f3a6825c-0ec3-4992-9c24-c4aa2144a893.png)

Eu achei estranho que o seu comando "boss init" não efetuou as perguntas igual foi feito no meu teste. 
Tem alguma coisa diferente ai?

**Comment by WhebertonFialho** [comment]
por isso acho estranho, qualquer comando que eu do para o boss aparece sempre a mesma coisa...

fiz a instalação manual... baixei o ultimo executavel boss... coloquei em uma pasta no disco C e adicioneis a variavel de ambiente e mesmo assim so aparece essas mensagem

**Comment by WhebertonFialho** [comment]
opa... resolvi... configurando novamente a ssh-key do computador e ele funcionou...

**Comment by viniciussanchez** [comment]
Legal... recentemente o Github teve uma alteração no Login dele mesmo. Inclusive no nosso grupo no Telegram, várias pessoas tiverem problemas. Mas nenhum igual o seu rsrsrs
Que bom que deu certo...
