### ISSUE TITLE
Boss & bitbucket ?

### ISSUE THREAD

**Issue by eduardomrj** [HashLoad/boss#75]
É possível clonar repositorios do bitbucket ?
Obrigado

**Comment by viniciussanchez** [comment]
Sim... qualquer servidor git

**Comment by eduardomrj** [comment]
Como faz para colocar login e senha na autenticação do bitbucket ?

**Comment by viniciussanchez** [comment]
```bash
boss login
```
dai só seguir os passos... aconselho usar sempre ssh
