### ISSUE TITLE
Multiplos DPR/LPR em um boss.json

### ISSUE THREAD

**Issue by chacalfloripa** [HashLoad/boss#81]
Seria interessante por incluir mais de um DPR/LPR em um projeto boss, isso seria muito útil em projetos que existem vários módulos.

**Comment by viniciussanchez** [comment]
@chacalfloripa hoje já funciona assim. Se você tiver dois DPR onde se encontra o arquivo do Boss.json, ao fazer o boss install, você vai instalar a dependência nos dois projetos.
