### ISSUE TITLE
Comando "Boss update" apagando diretórios que não fazem parte das dependências

### ISSUE THREAD

**Issue by microprocessgit** [HashLoad/boss#85]
Se adicionarmos manualmente alguma biblioteca propria dentro da pasta modules quando usando 
boss update
o boss está apagando estas bibliotecas (pastas)

exemplo
modules\MeuPacoteDeComponentes  <<<< não está no boss.json
apos o comando este diretorio foi completamente apagado!

**Comment by arvanus** [comment]
Não sou do projeto, mas faz sentido este comportamento, pois a pasta deveria refletir o conteúdo do boss.json, se o componente não está na relação do arquivo subentende-se que o usuário removeu ele das dependências, consequentemente deve ser excluída a pasta

**Comment by viniciussanchez** [comment]
Bom dia... concordo com o @arvanus. Acho que o comportamento está correto. Precisava até fazer um teste com outras ferramentas como o npm por exemplo, e ver como ele se comporta nesse caso. Mas eu acho que está correto sim
