### ISSUE TITLE
Procurar pelo ficheiro `boss.json` antes de descarregar o repositório

### ISSUE THREAD

**Issue by gcarreno** [HashLoad/boss#93]
Boas a todos/as,

Estava debaixo da impressão que este utilitário era só para Delphi, mas pela descrição parece que existe suporte para Lazarus tb.
Com esta nova perceção, decidi tentar usar o boss em vês do OPM para configurar um projeto de teste em Ubuntu 22.04 64b.

A primeira coisa em que tropecei foi no facto de que não é intuitivo o que se deve meter depois do comando `install`
Mas vou criar um _issue_ só sobre isso.

O que me levou aqui é outro facto: Não existe um repositório de pacotes/módulos. E por esse facto se eu fizer
```console
$ boss install gcarreno/setup-lazarus
```
o programa vai buscar o repositório ao GitHub e **DEPOIS** é que percebe que não existe um ficheiro `boss.json`.

Acho que antes de sequer iniciar qq transferência, que pode ser custosa, o programa devia consultar o repositório para ver se encontra um ficheiro `boss.json`. Depois, tendo a certeza que o ficheiro é válido para a vossa convenção, é que devia iniciar a transferência do repositório.

Curioso, também, é o facto que mesmo depois de não encontrar um ficheiro `boss.json` ainda tenta compilar.
Não sei se tenta mesmo, mas no _output_ do comando é o que diz.

Grande abraço,
Gus

**Comment by viniciussanchez** [comment]
Obrigado pelo feedback. 
Vamos analisar o motivo dele estar tentando instalar a dependência, antes de verificar se o arquivo boss.json existe.

**Comment by gcarreno** [comment]
Boas Vinícius (@viniciussanchez),

> Obrigado pelo feedback.

Ora essa!! Obrigado eu pelo vosso esforço.

> Vamos analisar o motivo dele estar tentando instalar a dependência, antes de verificar se o arquivo boss.json existe.

Posso estar imensamente errado, mas ao que me parece, tendo somente o _output_ do comando em que especular,  vcs decidiram que primeiro populavam a _cache_ e depois verificavam se o ficheiro `boss.json` existe.

Como disse, estou a especular imenso pq não li o código fonte e só estou a basear dita especulação no _output_ do programa.

Grande abraço,
Gus

**Comment by andre-djsystem** [comment]
Não consegui reproduzir o problema. Ocorre apenas no Linux?
![image](https://user-images.githubusercontent.com/49646398/201395501-48829185-07e6-4dcc-9696-e271d0b9387a.png)
