### ISSUE TITLE
Melhor documentação para o comando `install`

### ISSUE THREAD

**Issue by gcarreno** [HashLoad/boss#94]
Boas a todos/as,

Lendo o ficheiro `README.md`, não deixa muito claro qual a sintaxe do que se deve usar após a palavra `install`.

Nesse ficheiro lê-se apenas: `install <dependency>`, sem haver uma explicação mais profunda sobre o que realmente o programa espera.

Pelas poucas tentativas que fiz, percebi que se não de usar uma sintaxe baseada no usuário/repositório do GitHub e só usar um nome, por exemplo `horse` ele procura pela dependência debaixo da vossa organização `HashLoad`.

No entanto se usar isto: `gcarreno/setup-lazarus`, então o programa vai procurar por um repositório chamado `setup-lazarus` no usuário-organização `gcarreno` que exista no GitHub.

Seria bastante útil saber isto de antemão.

Grande abraço,
Gus

**Comment by viniciussanchez** [comment]
Obrigado....
Sim você tem razão. 
boss install horse -> vai procurar no github da hashload o projeto horse
boss install vinicius/horse -> vai procurar no github do vinicius o projeto horse
boss install gitlab/vinicius/horse -> vai procurar no gitlab do vinicius, o projeto horse
Fique a vontade também se quiser mandar um pull request, melhorando a documentação. Será bem vinda a sua contribuição!

**Comment by gcarreno** [comment]
Boas Vinícius (@viniciussanchez),

> Fique a vontade também se quiser mandar um pull request, melhorando a documentação. Será bem vinda a sua contribuição!

Agora é que me deixaste envergonhado, LOL 🤣

Estava a ver se conseguia passar despercebido e evitar trabalho da minha parte. Sim, sou bem preguiçoso 🤣

Ok, eu trato disso, mas preciso de mais info:
Os três exemplos acima são bons, mas noutro _issue_ li que tb se pode usar um URL completo, tipo:
`https://github.com/gcarreno/nosodata`, certo, errado?

E tenho de mencionar _case sensitive_ ou não?

Grande abraço,
Gus

**Comment by viniciussanchez** [comment]
Isso mesmo... pode sim

**Comment by gcarreno** [comment]
Boas Vinícius(@viniciussanchez),

> Isso mesmo... pode sim

Isto responde à minha 1ª pergunta, mas não à minha 2ª pergunta:

A string da dependência é tratado com `case sensitiveness` ou não?

Grande abraço,
Gus

**Comment by viniciussanchez** [comment]
Eu não testei. Mas acredito que isso seja de acordo com a plataforma que esteja utilizando. Por exemplo: se para acessar um projeto no github o github trate a URL como `case sensitiveness`, então a resposta para a sua pergunta é sim. Caso contrário é não. Mas não posso afirmar isso. Teria que testar

**Comment by gcarreno** [comment]
Boas Vinícius(@viniciussanchez),

Num dos meus testes editei o ficheiro `boss.json` à mão pq percebi que se usasse:
```console
$ boss i gcarreno/NosoData
```
ele pegava nessa string e punha tudo em minúsculas.

Fiquei com essa impressão qd estava a dar uma olhada na diretoria `~/.boss/cache`. Mas não tenho bem a certeza.

O que tenho bem a certeza é que qd estava a limpar a cache à mão, tinha 2 entradas para o mesmo repositório:
- `https://github.com/gcarreno/NosoData`
- `https://github.com/gcarreno/nosodata`

Portanto, **pelo menos**, na cache as coisas são tratadas com _case sensitiveness_.

Grande abraço,
Gus
