### ISSUE TITLE
O ficheiro `boss.json` deveria ter uma entrada para diferenciar o tipo de projeto

### ISSUE THREAD

**Issue by gcarreno** [HashLoad/boss#98]
Boas,

Pelo que entendo (sim com tão pouco tempo de utilização :smile:) do propósito do ficheiro `boss.json` entendo que seja utilizado de duas maneiras:
1. Para descrever uma dependência de modo a que seja identificada como válida qd o programa indaga um repositório
2. Para servir como um ficheiro que contêm as dependências de um projeto.

No entanto, qd estamos a programar uma aplicação, e não uma dependência, o programa deveria distinguir entre os dois.

Neste caso, se alguém tenta incluir uma dependência que seja uma aplicação, o programa pode rejeitar com um erro.

Proponho um novo membro no objeto principal do ficheiro `boss.json`:
- type: [ application | module ]

```json
{
  "type": "module",
  "name": "myModule",
/* ... */
}
```
Assim a distinção é clara e evita que se adicione uma dependência em erro.

Grande abraço,
Gus

**Comment by snakeice** [comment]
Opa, creio que a pessoa que vá instalar algo deve estar ciente e entender o que ela estiver instalando faz, até faz sentido instalar alguma application, esse projeto [bpl-identifier](https://github.com/HashLoad/bpl-identifier) é um application utilizada e instalada pelo boss, não se se devemos ter um campo e barrar a instalação de tal forma.
