### ISSUE TITLE
Existe a distinção entre dependências e dependências DEV?

### ISSUE THREAD

**Issue by gcarreno** [HashLoad/boss#99]
Boas,

Noutros gestores de dependências existem duas entradas para dependências:
1. dependencies(npm), require(composer)
2. devDependencies(npm), require-dev(composer)

O mesmo existe para este programa?

Grande abraço,
Gus

**Comment by snakeice** [comment]
Opa, não existe, até então não vimos necessidade de implementar 😅, mas pode ser algo a se considerar em uma alguma futura versão
